pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                  buildctl --version
                  kubectl version
                  helm version
                '''
            }
        }
        stage('Build') {
            steps {
              echo "Building image tag: docker.io/twkji/file-server"
              dir ('./test1') {
                sh '''
                  buildctl --addr tcp://buildkitd:1234 \
                  build \
                  --frontend dockerfile.v0 \
                  --local context=./ \
                  --local dockerfile=./ \
                  --output type=image,name=docker.io/twkji/file-server,push=true
                '''
              }
            }
        }
        stage('Run') {
            steps {
              echo "Deploying to test"
              dir ('./test1') { 
                sh 'helm upgrade --install --atomic \
                      --set registryServer=docker.io,registryUser=twkji \
                      --namespace default \
                      file-server \
                  ./helm/file-server'
              }
            }
        }
    }
}
