pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                  buildctl --version
                  kubectl version
                  helm version
                '''
            }
        }
        stage('Build') {
            steps {
              echo "Building image tag: docker.io/twkji/file-server"
              dir ('./test1') {
                sh '''
                  buildctl --addr tcp://buildkitd:1234 \
                  build \
                  --frontend dockerfile.v0 \
                  --local context=./ \
                  --local dockerfile=./ \
                  --output type=image,name=docker.io/twkji/file-server,push=true
                '''
              }
            }
        }
        stage('Run') {
            steps {
              echo "Deleting existing release (if any)"
              // 기존 Helm 릴리스를 삭제
              sh '''
                helm uninstall file-server --namespace devops-tools || true
              '''
              echo "Deploying new release"
              // 새로운 Helm 릴리스를 설치
              dir ('./test1') { 
                sh '''
                  helm install file-server ./helm/file-server \
                    --atomic \
                    --set registryServer=docker.io,registryUser=twkji \
                    --namespace devops-tools
                '''
              }
            }
        }
    }
}
