apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
      - name: file-server
        image: twkji/file-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: parameters-volume
          mountPath: /mnt/parameters
      volumes:
      - name: parameters-volume
        persistentVolumeClaim:
          claimName: parmeters-volume-test