apiVersion: v1
kind: Service
metadata:
  name: file-server-service
spec:
  type: NodePort  # NodePort로 변경
  selector:
    app: file-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007  # 외부에서 접근 가능한 포트 (임의 지정 가능, 30000~32767 범위)
