replicas: 1

image:
  repository: twkji/file-server
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30007 # 30000~32767 범위 내에서 지정

persistentVolumeClaimName: parmeters-volume-test
